### ISSUE TITLE
Beta channel arm64 images missing from AWS

### ISSUE THREAD

**Issue by mtougeron** [flatcar-linux/Flatcar#570]
## Description

Beta channel arm64 images missing from AWS us-east-1 and us-west-2 (I haven't checked other the regions) even though they are listed as available on https://www.flatcar-linux.org/docs/latest/installing/cloud/aws-ec2/

I'm not sure if this is an issue with the images on AWS or if it is a documentation problem.

## Impact

Unable to use/test arm64 images of Flatcar in AWS

**Comment by dongsupark** [comment]
Thanks for the bug report.
Indeed Beta arm64 images are set to private. Alpha arm64 are already public.
We will soon try to fix that.

**Comment by mtougeron** [comment]
Thanks for the quick response!

**Comment by dongsupark** [comment]
Published `Flatcar-beta-3033.1.0-arm64-hvm` and `Flatcar-beta-3033.1.1-arm64-hvm` for all AWS regions.
So the issue should be resolved.
If there is still a problem about that, feel free to reopen. Thanks.

**Comment by mtougeron** [comment]
Awesome thanks! I see them now. 
![image](https://user-images.githubusercontent.com/37266/145620526-bcd5dbf8-f292-4e76-84a4-fc57a1df7283.png)
